### ISSUE TITLE
_reactNativeFitness.default.PermissionKind.Step is undefined

### ISSUE THREAD

**Issue by anshgupta1234** [OvalMoney/react-native-fitness#52]
Copying straight out of the example, I have this code here:

```
import Fitness from '@ovalmoney/react-native-fitness';

getHealthData = () => {
    const permissions = [
      { kind: Fitness.PermissionKind.Step, access: Fitness.PermissionAccess.Write },
    ];

    Fitness.isAuthorized(permissions)
      .then((authorized) => {
        console.warn(Fitness.getSteps({ startDate: new Date(2020, 4, 12) }))
      })
      .catch((error) => {
        // Do something
      });
  };
```

However, it's throwing me an error saying that PermissionKind.Step is undefined. Any idea to why this might be?

**Comment by brar07** [comment]
Yeah, I have got same issue. "Steps" didn't work either.

**Comment by brar07** [comment]
I think the issue is Expo. I was trying this on Expo project, maybe the same is your or others' case too. One needs to eject for it to work properly. But, I suggest if you do eject, don't use this code, rather, try the native code. Find it from Stackoverflow and try the native modules and then send that data to your React Native project.

**Comment by GuleriaAshish** [comment]
The issue we are using javascript class for every function but every new functionality and functions are implemented in typescript class. And we are trying to get all those functions from index.js class.

**Comment by Francesco-Voto** [comment]
Hi @brar07 ,

Yes you cannot use this library with Expo Projects
